# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170524_0423'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='base_menu',
            table='Article',
        ),
    ]
